[package]
name = "kube_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7"
chrono = "0.4"
k8s-openapi = { version = "0.22.0", features = ["latest"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["raw_value"] }
