[package]
name = "market"
version = "0.1.0"
edition = "2021"

[features]
default = ["mimalloc"]

# Enable mimalloc
mimalloc = []
# Enable jaeger
jaeger = [
    "opentelemetry",
    "opentelemetry-jaeger",
    "reqwest-tracing",
    "tracing-opentelemetry",
    "tracing-actix-web",
]

[dependencies]
actix-web = "4.2.1"
actix-web-opentelemetry = "0.13.0"
anyhow = "1.0.58"
base64 = { version = "0.13.0", default-features = false, features = [
    "alloc", # for base64::decode_config and base64::encode_config
] }
bytes = "1.2.0"
chrono = "0.4"
futures = "0.3.28"
influxdb2 = "0.4.2"
influxdb2-derive = "0.1.1"
influxdb2-structmap = "0.2"
num-traits = "0.2"
lazy-regex = "2.3.0"
lazy_static = "1.4.0"
# log = "0.4.17"
mimalloc = { version = "0.1.32", default-features = false }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.17.0", features = [
    "reqwest_collector_client",
    "rt-tokio",
], default-features = false, optional = true }
reqwest = { version = "0.11.11", features = ["json", "gzip"] }
reqwest-middleware = "0.2.0"
reqwest-tracing = { version = "0.4.0", features = [
    "opentelemetry_0_18",
], optional = true }
ron = "0.8.0"
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_json = { version = "1.0.82", features = ["raw_value"] }
serde_with = "2.0.0"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.37"
tracing-actix-web = { version = "0.7.2", features = [
    "opentelemetry_0_18",
], optional = true }
tracing-appender = "0.2"
tracing-forest = { version = "0.1.5", features = ["tokio"] }
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-opentelemetry = { version = "0.18.0", optional = true }
uom = { version = "0.34.0", default-features = false, features = [
    "f64",
    "si",
    "autoconvert",
] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }

helper = { path = "../helper" }
helper_derive = { path = "../helper_derive" }
model = { path = "../model" }
