[package]
name = "market"
version = "0.1.0"
edition = "2021"

[features]
default = ["mimalloc"]

# Enable mimalloc
mimalloc = []

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
base64 = { version = "0.13.0", default-features = false, features = [
    "alloc", # for base64::decode_config and base64::encode_config
] }
bytes = "1.2.0"
chrono = "0.4"
env_logger = "0.10"
futures = "0.3.21"
lazy-regex = "2.3.0"
lazy_static = "1.4.0"
log = "0.4.17"
mimalloc = { version = "0.1.32", default-features = false }
okapi = { version = "0.7.0-rc.1", features = ["impl_json_schema"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
rocket = "0.5.0-rc.2"
rocket_okapi = { version = "0.8.0-rc.2", features = ["swagger", "uuid"] }
ron = "0.8.0"
schemars = "0.8"
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_json = { version = "1.0.82", features = ["raw_value"] }
serde_with = "2.0.0"
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "time", "sync"] }
uom = { version = "0.33.0", default-features = false, features = [
    "f64",
    "si",
    "autoconvert",
] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }

helper = { path = "../helper" }
model = { path = "../model" }
