# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: [--maxkb=1000]
- repo: local
  hooks:
    - id: cargo-fmt
      name: cargo-fmt
      entry: bash -c 'cd manager && cargo fmt'
      language: system
      types: [rust]
      pass_filenames: false
- repo: local
  hooks:
    - id: check-compilation
      name: check-compile-manager
      entry: bash -c 'cd manager && just docker'
      language: system
      types: [rust]
      pass_filenames: false
- repo: local
  hooks:
    - id: clippy
      name: clippy
      entry: bash -c 'cd manager && just clippy'
      language: system
      types: [rust]
      pass_filenames: false
