[workspace]
resolver = "2"
members = [
    "fog_node",
    "market",
    "helper",
    "helper_derive",
    "model",
    "kube_metrics",
    "openfaas",
]

[profile.release]
strip = true
# lto = true
lto = "thin"
opt-level = 3
codegen-units = 1
