global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "127.0.0.1:3091"
  - job_name: "iot"
    static_configs:
      - targets: 
        - "127.0.0.1:30080"
