[package]
name = "iot_emulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
flurry = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
rocket = { version = "0.5.0-rc.2", features = ["json"]}
rocket_prometheus = "0.10.0-rc.3"
serde = { version = "1.0.139", features = ["derive", "rc"] }
serde_json = { version = "1.0.82", features = ["raw_value"] }
tokio = { version = "1.20.0", features = ["full"] }
#tokio-cron-scheduler = "0.7.4"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }
