schema = 3

[mod]
  [mod."github.com/apapsch/go-jsonmerge/v2"]
    version = "v2.0.0"
    hash = "sha256-xp/1B6XUN2EbddBfoUkTV3oTk+34m4kOZP+66HhfLg4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/deepmap/oapi-codegen"]
    version = "v1.12.4"
    hash = "sha256-VbaGFTDfe/bm4EP3chiG4FPEna+uC4HnfGG4C7YUWHc="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.2"
    hash = "sha256-laV+IkgbnEG07h1eFfPISqp0ctnLXfzchz/CLR1lftk="
  [mod."github.com/go-logr/logr"]
    version = "v1.3.0"
    hash = "sha256-N8JYtQlwpLWTaCczfhfA/YmHExko0ObPMYVGw8JwbSw="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.16.0"
    hash = "sha256-ewMfH1WuN1QHbo27HMo6puDiWHC5qYISTTMhRay2fwI="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/uuid"]
    version = "v1.4.0"
    hash = "sha256-FU0gzLmS48Ik9T+quGg5z/7ESGMPSXM3SY+rdJtG+5w="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.16.0"
    hash = "sha256-OkHsxyj6YjE7T5rvBC/5AqF3MDezw0WAFetqEVB1MSc="
  [mod."github.com/influxdata/influxdb-client-go/v2"]
    version = "v2.12.4"
    hash = "sha256-8M3MTTogrPng8xHCGy0uyrcfyEFCL1yFSPDlt1IumCM="
  [mod."github.com/influxdata/line-protocol"]
    version = "v0.0.0-20200327222509-2487e7298839"
    hash = "sha256-U5aoGA5j6UtR3lYAj0o71jCPF1er4ynzWyCPcpuTye4="
  [mod."github.com/leodido/go-urn"]
    version = "v1.2.4"
    hash = "sha256-N2HO7ChScxI79KGvXI9LxoIlr+lkBNdDZP9OPGwPRK0="
  [mod."github.com/uptrace/opentelemetry-go-extra/otelutil"]
    version = "v0.2.3"
    hash = "sha256-fEHqHUvCvJTfNFkh4HioOuLA+eKipCGXW04a0l4iSAM="
  [mod."github.com/uptrace/opentelemetry-go-extra/otelzap"]
    version = "v0.2.3"
    hash = "sha256-Rf3hJRgyVedOhqhayVl1kACWzVhbKHZY1j6pzGeeoh8="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.46.1"
    hash = "sha256-H7GeyxyGcxVRCnR0J7HvpWi3QhwsXGF/IunQMpfkXhw="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.21.0"
    hash = "sha256-MWC1fp41z3w3Y1wlECY12Q7sLeU4PRACZEesWTmDD9E="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.21.0"
    hash = "sha256-eljoB40gDVLeNjg/NZdMXi1M7uUKQ/XBcA2MG9pf8pY="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.21.0"
    hash = "sha256-H4MhWbS0c42mHE96vGIxolRe5VVPu2/0sqC4oVjwZ+c="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.21.0"
    hash = "sha256-UH5fN59juP5GRiTpr5VUv4JGAE2o47LOyR7Ic6Yl/v4="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.21.0"
    hash = "sha256-zVeXCf3jVEWjLdOYty//nCpzBtejZET0tEOQyONJ3Mo="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.21.0"
    hash = "sha256-vjZsOaQCgTjz6WYim0YZHLnB/PC3CvTSpS97qkL2vz8="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.0.0"
    hash = "sha256-w2WbhXXshdm/ZmZkg5VpWwXFLjJRBBwSObyHGjJcELQ="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.26.0"
    hash = "sha256-EUQnALSDtoJryWp01K/PMbRUvQYG1uDbqGnlJ/7thE4="
  [mod."golang.org/x/crypto"]
    version = "v0.14.0"
    hash = "sha256-UUSt3X/i34r1K0mU+Y5IzljX5HYy07JcHh39Pm1MU+o="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/sys"]
    version = "v0.14.0"
    hash = "sha256-ReIRQmONicRW9idzGVPCBx5TTcKacmQTF1vPC3L4SxY="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-qd9dJezVHNJZNMkywXapT1rsyD+lb25AU8aG8NJlhm4="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230911183012-2d3300fd4832"
    hash = "sha256-1kP7lqQ+fKtARDzTrRNob0owX4GsUnxzOwLyBZSmHOc="
  [mod."google.golang.org/grpc"]
    version = "v1.59.0"
    hash = "sha256-IcwmXyeroUg742wqU4Zikwxm7y0i7x4axOPdWOGPkzE="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
