[tool.poetry]
name = "live"
version = "0.1.0"
description = "Experiment facilities for the Fog"
authors = ["Volodia PAROL-GUARINO <volodia.parol-guarino@proton.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
# Fixes <clock offset="localtime"/> to utc, leading to fix of k3s certificate being generated for an jour in the future from the pov of the vm
enoslib = { git = "https://gitlab.inria.fr/vparolgu/enoslib.git" }
click = "^8.1"
setuptools = "^65.6.3"

# [tool.poetry.dev-dependencies]
# black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 140
