[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
bytes = "1.2.0"
chrono = "0.4"
dashmap = "5.4.0"
futures = "0.3.21"
lazy-regex = "2.3.0"
lazy_static = "1.4.0"
log = "0.4.17"
ron = "0.8.0"
schemars = "0.8"
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_json = { version = "1.0.82", features = ["raw_value"] }
serde_with = "2.0.0"
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["full"] }
uom = { version = "0.33.0", default-features = false, features = [
    "f64",
    "si",
    "autoconvert",
] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }
helper = { path = "../helper" }
