[package]
name = "fog_node"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[features]
default = ["mimalloc"]
# Enables fake implementation of kubernetes not to rely on a true one
fake_k8s = []
# Enable the bottom up placement method (placing at Edge first)
bottom_up_placement = []
# Enable mimalloc
mimalloc = []

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
base64 = { version = "0.13.1", default-features = false, features = [
    "alloc", # for base64::decode_config and base64::encode_config
] }
bytes = "1.2.0"
chrono = "0.4.23"
dashmap = "5.4.0"
drpc = "0.2.0"
futures = "0.3.25"
k8s-openapi = { version = "0.16.0", features = ["v1_25"] }
kube = { version = "0.76.0", default-features = false, features = ["client", "runtime", "rustls-tls"] }
lazy-regex = "2.3.1"
lazy_static = "1.4.0"
mimalloc = { version = "0.1.32", default-features = false }
num_cpus = "1.14.0"
okapi = { version = "0.7.0-rc.1", features = ["impl_json_schema"] }
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls"] }
rocket = "0.5.0-rc.2"
rocket_okapi = { version = "0.8.0-rc.2", features = ["swagger", "uuid"] }
rocket_prometheus = "0.10.0-rc.3"
ron = "0.8.0"
schemars = "0.8.11"
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = { version = "1.0.87", features = ["raw_value"] }
serde_with = "2.0.1"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"
tracing-appender = "0.2"
tracing-subscriber = {version = "0.3.16", features = ["env-filter"]}
tracing-forest = { version = "0.1.5", features = ["tokio"]}
uom = { version = "0.33.0", default-features = false, features = [
    "f64",
    "si",
    "autoconvert",
] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "serde"] }

helper = { path = "../helper" }
kube_metrics = { path = "../kube_metrics" }
model = { path = "../model" }
openfaas = { path = "../openfaas" }
