[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
chrono = "0.4"
lazy-regex = "2.3.0"
reqwest = { version = "0.11.12", features = ["json", "gzip"] }
ron = "0.8.0"
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_json = { version = "1.0.82", features = ["raw_value"] }
serde_with = "2.0.0"
thiserror = "1.0.31"
uom = { version = "0.33.0", default-features = false, features = [
    "f64",
    "si",
    "autoconvert",
] }
