---
- include_tasks: config_prometheus.yml

- name: Installing Prometheus
  docker_container:
    name: prometheus
    image: ghcr.io/volodiapg/prometheus:latest
    detach: true
    state: started
    recreate: true
    auto_remove: true
    cleanup: true
    keep_volumes: false
    network_mode: host
    command: --config.file=/prometheus/prometheus.yml --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --web.enable-admin-api
    volumes:
      - "{{ remote_working_dir }}/prometheus.yml:/prometheus/prometheus.yml"
